server:
  port: 8081
spring:
  application:
    name: hospital-service
  data:
    mongodb:
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      database: hospital-db
      repositories:
        enabled: 'true'